# GitHub Sponsors (https://github.com/sponsors)
github: Robbbo-T

# Custom sponsorship URLs
custom:
  - https://www.patreon.com/Robbbo_T
  - https://ko-fi.com/Robbbo_T

# Other funding platforms
open_collective: robbbo-open-collective
patreon: Robbbo_T
tidelift: robbbo-package

# Research and Specialized Support
custom:
  - https://experiment.com/users/RobbboT
  - https://fastgrants.org/apply

# Crowdfunding for specific projects
custom:
  - https://www.kickstarter.com/profile/Robbbo-T
