const fs = require('fs');
const path = require('path');

// Function to generate a simple HTML page
function generateHTML() {
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Generated UI</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          background-color: #f0f0f0;
        }
        .container {
          text-align: center;
          background-color: #fff;
          padding: 20px;
          border-radius: 8px;
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Welcome to the Generated UI</h1>
        <p>This is a simple HTML page generated by the script.</p>
      </div>
    </body>
    </html>
  `;

  const outputPath = path.join(__dirname, 'generated-ui.html');
  fs.writeFileSync(outputPath, htmlContent, 'utf8');
  console.log(`HTML page generated at: ${outputPath}`);
}

// Run the function to generate the HTML page
generateHTML();
