name: Create API Integration Repository Structure

on:
  workflow_dispatch:

jobs:
  create-structure:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up directory structure
        run: |
          mkdir -p adaptation-layer/src
          mkdir -p microservices-facades/src
          mkdir -p transformation-framework/src
          mkdir -p metadata-driven-approach/src
          mkdir -p api-orchestration/src
          mkdir -p common/src
          mkdir -p docs/diagrams
          mkdir -p docs/air/00
          mkdir -p docs/air/01
          mkdir -p docs/air/02
          mkdir -p docs/air/03
          mkdir -p docs/air/04
          mkdir -p docs/air/05
          mkdir -p docs/air/06
          mkdir -p docs/air/07
          mkdir -p docs/air/08
          mkdir -p docs/air/09
          mkdir -p docs/air/10
          mkdir -p docs/air/11
          mkdir -p docs/air/12
          mkdir -p docs/air/13
          mkdir -p docs/air/14
          mkdir -p docs/air/15
          mkdir -p docs/air/16
          mkdir -p docs/air/17
          mkdir -p docs/air/18
          mkdir -p docs/air/19
          mkdir -p docs/air/20
          mkdir -p docs/air/21
          mkdir -p docs/air/22
          mkdir -p docs/air/23
          mkdir -p docs/air/24
          mkdir -p docs/air/25
          mkdir -p docs/air/26
          mkdir -p docs/air/27
          mkdir -p docs/air/28
          mkdir -p docs/air/29
          mkdir -p docs/air/30
          mkdir -p docs/air/31
          mkdir -p docs/air/32
          mkdir -p docs/air/33
          mkdir -p docs/air/34
          mkdir -p docs/air/35
          mkdir -p docs/air/36
          mkdir -p docs/air/37
          mkdir -p docs/air/38
          mkdir -p docs/air/39
          mkdir -p docs/air/40
          mkdir -p docs/air/41
          mkdir -p docs/air/42
          mkdir -p docs/air/43
          mkdir -p docs/air/44
          mkdir -p docs/air/45
          mkdir -p docs/air/46
          mkdir -p docs/air/47
          mkdir -p docs/air/48
          mkdir -p docs/air/49
          mkdir -p docs/air/50
          mkdir -p docs/air/51
          mkdir -p docs/air/52
          mkdir -p docs/air/53
          mkdir -p docs/air/54
          mkdir -p docs/air/55
          mkdir -p docs/air/56
          mkdir -p docs/air/57
          mkdir -p docs/air/58
          mkdir -p docs/air/59
          mkdir -p docs/air/60
          mkdir -p docs/air/61
          mkdir -p docs/air/62
          mkdir -p docs/air/63
          mkdir -p docs/air/64
          mkdir -p docs/air/65
          mkdir -p docs/air/66
          mkdir -p docs/air/67
          mkdir -p docs/air/68
          mkdir -p docs/air/69
          mkdir -p docs/air/70
          mkdir -p docs/air/71
          mkdir -p docs/air/72
          mkdir -p docs/air/73
          mkdir -p docs/air/74
          mkdir -p docs/air/75
          mkdir -p docs/air/76
          mkdir -p docs/air/77
          mkdir -p docs/air/78
          mkdir -p docs/air/79
          mkdir -p docs/air/80
          mkdir -p docs/air/81
          mkdir -p docs/air/82
          mkdir -p docs/air/83
          mkdir -p docs/air/84
          mkdir -p docs/air/85
          mkdir -p docs/air/86
          mkdir -p docs/air/87
          mkdir -p docs/air/88
          mkdir -p docs/air/89
          mkdir -p docs/air/90
          mkdir -p docs/air/91
          mkdir -p docs/air/92
          mkdir -p docs/air/93
          mkdir -p docs/air/94
          mkdir -p docs/air/95
          mkdir -p docs/air/96
          mkdir -p docs/air/97
          mkdir -p docs/air/98
          mkdir -p docs/air/99
          mkdir -p docs/space/ss/10
          mkdir -p docs/space/ss/20
          mkdir -p docs/space/ss/30
          mkdir -p docs/space/ss/40
          mkdir -p docs/space/ss/50
          mkdir -p docs/space/ss/60
          mkdir -p docs/space/ss/70
          mkdir -p docs/space/ss/80
          mkdir -p docs/space/ss/90
          mkdir -p docs/space/mo/10
          mkdir -p docs/space/mo/20
          mkdir -p docs/space/mo/30
          mkdir -p docs/space/mo/40
          mkdir -p docs/space/mo/50
          mkdir -p docs/space/mo/60
          mkdir -p docs/space/mo/70
          mkdir -p docs/space/mo/80
          mkdir -p docs/space/mo/90
          mkdir -p docs/space/se/10
          mkdir -p docs/space/se/20
          mkdir -p docs/space/se/30
          mkdir -p docs/space/se/40
          mkdir -p docs/space/se/50
          mkdir -p docs/space/se/60
          mkdir -p docs/space/se/70
          mkdir -p docs/space/se/80
          mkdir -p docs/space/se/90
          mkdir -p docs/space/ls/10
          mkdir -p docs/space/ls/20
          mkdir -p docs/space/ls/30
          mkdir -p docs/space/ls/40
          mkdir -p docs/space/ls/50
          mkdir -p docs/space/ls/60
          mkdir -p docs/space/ls/70
          mkdir -p docs/space/ls/80
          mkdir -p docs/space/ls/90
          mkdir -p docs/space/sr/10
          mkdir -p docs/space/sr/20
          mkdir -p docs/space/sr/30
          mkdir -p docs/space/sr/40
          mkdir -p docs/space/sr/50
          mkdir -p docs/space/sr/60
          mkdir -p docs/space/sr/70
          mkdir -p docs/space/sr/80
          mkdir -p docs/space/sr/90
          mkdir -p docs/common/fd
          mkdir -p docs/common/cn
          mkdir -p docs/common/gb
          mkdir -p docs/common/supl
          mkdir -p docs/common/rame
          mkdir -p docs/common/pm
          mkdir -p docs/common/ds
          mkdir -p docs/common/dimensions
          mkdir -p docs/common/rs
          mkdir -p docs/GP-AM/00
          mkdir -p docs/GP-AM/01
          mkdir -p docs/GP-AM/02
          mkdir -p docs/GP-AM/03
          mkdir -p docs/GP-AM/04
          mkdir -p docs/GP-AM/05
          mkdir -p docs/GP-AM/06
          mkdir -p docs/GP-AM/07
          mkdir -p docs/GP-AM/08
          mkdir -p docs/GP-AM/09
          mkdir -p docs/GP-AM/10
          mkdir -p docs/GP-AM/11
          mkdir -p docs/GP-AM/12
          mkdir -p docs/GP-AM/13
          mkdir -p docs/GP-AM/14
          mkdir -p docs/GP-AM/15
          mkdir -p docs/GP-AM/16
          mkdir -p docs/GP-AM/17
          mkdir -p docs/GP-AM/18
          mkdir -p docs/GP-AM/19
          mkdir -p docs/GP-AM/20
          mkdir -p docs/GP-AM/21
          mkdir -p docs/GP-AM/22
          mkdir -p docs/GP-AM/23
          mkdir -p docs/GP-AM/24
          mkdir -p docs/GP-AM/25
          mkdir -p docs/GP-AM/26
          mkdir -p docs/GP-AM/27
          mkdir -p docs/GP-AM/28
          mkdir -p docs/GP-AM/29
          mkdir -p docs/GP-AM/30
          mkdir -p docs/GP-AM/31
          mkdir -p docs/GP-AM/32
          mkdir -p docs/GP-AM/33
          mkdir -p docs/GP-AM/34
          mkdir -p docs/GP-AM/35
          mkdir -p docs/GP-AM/36
          mkdir -p docs/GP-AM/37
          mkdir -p docs/GP-AM/38
          mkdir -p docs/GP-AM/39
          mkdir -p docs/GP-AM/40
          mkdir -p docs/GP-AM/41
          mkdir -p docs/GP-AM/42
          mkdir -p docs/GP-AM/43
          mkdir -p docs/GP-AM/44
          mkdir -p docs/GP-AM/45
          mkdir -p docs/GP-AM/46
          mkdir -p docs/GP-AM/47
          mkdir -p docs/GP-AM/48
          mkdir -p docs/GP-AM/49
          mkdir -p docs/GP-AM/50
          mkdir -p docs/GP-AM/51
          mkdir -p docs/GP-AM/52
          mkdir -p docs/GP-AM/53
          mkdir -p docs/GP-AM/54
          mkdir -p docs/GP-AM/55
          mkdir -p docs/GP-AM/56
          mkdir -p docs/GP-AM/57
          mkdir -p docs/GP-AM/58
          mkdir -p docs/GP-AM/59
          mkdir -p docs/GP-AM/60
          mkdir -p docs/GP-AM/61
          mkdir -p docs/GP-AM/62
          mkdir -p docs/GP-AM/63
          mkdir -p docs/GP-AM/64
          mkdir -p docs/GP-AM/65
          mkdir -p docs/GP-AM/66
          mkdir -p docs/GP-AM/67
          mkdir -p docs/GP-AM/68
          mkdir -p docs/GP-AM/69
          mkdir -p docs/GP-AM/70
          mkdir -p docs/GP-AM/71
          mkdir -p docs/GP-AM/72
          mkdir -p docs/GP-AM/73
          mkdir -p docs/GP-AM/74
          mkdir -p docs/GP-AM/75
          mkdir -p docs/GP-AM/76
          mkdir -p docs/GP-AM/77
          mkdir -p docs/GP-AM/78
          mkdir -p docs/GP-AM/79
          mkdir -p docs/GP-AM/80
          mkdir -p docs/GP-AM/81
          mkdir -p docs/GP-AM/82
          mkdir -p docs/GP-AM/83
          mkdir -p docs/GP-AM/84
          mkdir -p docs/GP-AM/85
          mkdir -p docs/GP-AM/86
          mkdir -p docs/GP-AM/87
          mkdir -p docs/GP-AM/88
          mkdir -p docs/GP-AM/89
          mkdir -p docs/GP-AM/90
          mkdir -p docs/GP-AM/91
          mkdir -p docs/GP-AM/92
          mkdir -p docs/GP-AM/93
          mkdir -p docs/GP-AM/94
          mkdir -p docs/GP-AM/95
          mkdir -p docs/GP-AM/96
          mkdir -p docs/GP-AM/97
          mkdir -p docs/GP-AM/98
          mkdir -p docs/GP-AM/99
          mkdir -p docs/GP-AS/10
          mkdir -p docs/GP-AS/20
          mkdir -p docs/GP-AS/30
          mkdir -p docs/GP-AS/40
          mkdir -p docs/GP-AS/50
          mkdir -p docs/GP-AS/60
          mkdir -p docs/GP-AS/70
          mkdir -p docs/GP-AS/80
          mkdir -p docs/GP-AS/90
